"""
DataPilot MCP — Explain Chart Route
POST /api/explain-chart

Accepts a Chart.js config + underlying data, returns a plain-English
explanation of what the chart shows generated by the LLM router.
"""

import logging

from flask import Blueprint, jsonify, request

from backend.llm import router as llm_router

logger = logging.getLogger(__name__)

explain_chart_bp = Blueprint("explain_chart", __name__)

_SYSTEM_PROMPT = (
    "You are a senior data analyst. A user has just viewed a chart and wants "
    "a clear, plain-English explanation of what it shows. "
    "Be concise (3-5 sentences). Highlight the most important trend, comparison, "
    "or insight visible in the data. Do not use jargon or bullet points — "
    "write a short paragraph as if briefing a non-technical executive."
)


@explain_chart_bp.route("/api/explain-chart", methods=["POST"])
def explain_chart():
    """
    Generate a plain-English explanation of a chart.

    Request JSON:
        {
            "chart_type": "bar" | "line" | "pie" | "scatter",
            "chart_config": { ...Chart.js config... },
            "columns": ["col1", "col2", ...],
            "rows": [[val, val], ...]
        }

    Response JSON (success):
        { "explanation": "..." }

    Response JSON (error):
        { "error": "..." }
    """
    data = request.get_json(silent=True)
    if not data:
        return jsonify({"error": "Request body must be JSON."}), 400

    chart_type = (data.get("chart_type") or "").strip()
    chart_config = data.get("chart_config") or {}
    columns = data.get("columns") or []
    rows = data.get("rows") or []

    if not chart_config:
        return jsonify({"error": "Field 'chart_config' is required."}), 400

    user_message = _build_user_message(chart_type, chart_config, columns, rows)

    try:
        response = llm_router.complete(
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user",   "content": user_message},
            ],
            temperature=0.4,
            max_tokens=512,
        )
        explanation = (response.get("content") or "").strip()
        if not explanation:
            return jsonify({"error": "LLM returned an empty explanation."}), 500

        return jsonify({"explanation": explanation}), 200

    except RuntimeError as exc:
        logger.error("explain-chart LLM error: %s", exc)
        return jsonify({"error": "Could not generate explanation — LLM unavailable."}), 503
    except Exception as exc:
        logger.exception("explain-chart unexpected error: %s", exc)
        return jsonify({"error": "Unexpected error generating explanation."}), 500


# ------------------------------------------------------------------
# Helpers
# ------------------------------------------------------------------

def _build_user_message(chart_type: str, chart_config: dict, columns: list, rows: list) -> str:
    """Compose the user-facing LLM prompt from chart metadata + a data sample."""
    lines = []

    if chart_type:
        lines.append(f"Chart type: {chart_type}")

    # Extract labels and dataset summaries from the Chart.js config
    cfg_data = chart_config.get("data", {})
    labels = cfg_data.get("labels", [])
    datasets = cfg_data.get("datasets", [])

    if labels:
        sample_labels = labels[:20]
        lines.append(f"Labels ({len(labels)} total, showing first {len(sample_labels)}): {sample_labels}")

    for ds in datasets[:3]:  # cap at 3 datasets
        ds_label = ds.get("label", "dataset")
        ds_data = ds.get("data", [])
        sample = ds_data[:20]
        lines.append(f"Dataset '{ds_label}' ({len(ds_data)} points, showing first {len(sample)}): {sample}")

    # Add a compact data sample if rows are provided
    if columns and rows:
        lines.append(f"Columns: {columns}")
        sample_rows = rows[:10]
        lines.append(f"Data sample ({len(rows)} rows total, showing first {len(sample_rows)}):")
        for row in sample_rows:
            lines.append(f"  {row}")

    lines.append("\nPlease explain what this chart shows.")
    return "\n".join(lines)
